services:
    postgres:
        container_name: postgres
        image: postgres:12
        environment:
            POSTGRES_USER: oni
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: oni
        ports:
          - "5432:5432"
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: oni@nikic.org
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - "80:80"
